services:
  # DATABASE SERVICES
  mongodb-designer:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-designer
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '${MONGO_PORT_DESIGNER}:27017'
    volumes:
      - mongo-designer:/data/db
    networks:
      - leia-network

  mongodb-workbench:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-workbench
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '${MONGO_PORT_WORKBENCH}:27017'
    volumes:
      - mongo-workbench:/data/db
    networks:
      - leia-network

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    networks:
      - leia-network

  # BACKEND SERVICES
  designer-backend:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-designer-backend:latest
    container_name: designer-backend
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-designer:27017/designer?authSource=admin
      - FRONTEND_URL=${DESIGNER_FRONTEND_URL}
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - JWT_SECRET=${JWT_SECRET}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - API_KEY=${API_KEY}
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_KEY=${RUNNER_KEY}
    depends_on:
      - mongodb-designer
    ports:
      - '${PORT_DESIGNER_BACKEND}:80'
    networks:
      - leia-network

  workbench-backend:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-workbench-backend:latest
    container_name: workbench-backend
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-workbench:27017/workbench?authSource=admin
      - FRONTEND_URL=${WORKBENCH_FRONTEND_URL}
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_KEY=${RUNNER_KEY}
      - DESIGNER_BACKEND_URL=${DESIGNER_BACKEND_URL}
      - DESIGNER_BACKEND_KEY=${DESIGNER_BACKEND_KEY}
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - ADMIN_SECRET=${ADMIN_SECRET}
    depends_on:
      - mongodb-workbench
    ports:
      - '${PORT_WORKBENCH_BACKEND}:80'
    networks:
      - leia-network

  runner:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-runner:latest
    container_name: runner
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - RUNNER_KEY=${RUNNER_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EVALUATION_MODEL=${OPENAI_EVALUATION_MODEL:-gpt-4o}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-openai}
    depends_on:
      - redis
    ports:
      - '${PORT_RUNNER}:80'
    networks:
      - leia-network

  # FRONTEND SERVICES
  designer-frontend:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-designer-frontend:latest
    container_name: designer-frontend
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${PORT_DESIGNER_FRONTEND}:3000'
    networks:
      - leia-network

  workbench-frontend:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-workbench-frontend:latest
    container_name: workbench-frontend
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${PORT_WORKBENCH_FRONTEND}:3000'
    networks:
      - leia-network

volumes:
  mongo-designer:
  mongo-workbench:
  redis-data:

networks:
  leia-network:
    driver: bridge
