services:
  # DATABASE SERVICES
  mongodb-workbench:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-workbench
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '${MONGO_PORT_WORKBENCH}:27017'
    volumes:
      - mongo-workbench:/data/db
    networks:
      - leia-workbench-network

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: redis-workbench
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    networks:
      - leia-workbench-network

  # BACKEND SERVICES
  workbench-backend:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-workbench-backend:latest
    container_name: workbench-backend
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb-workbench:27017/workbench?authSource=admin
      - FRONTEND_URL=${WORKBENCH_FRONTEND_URL}
      - RUNNER_URL=${RUNNER_URL}
      - RUNNER_KEY=${RUNNER_KEY}
      - DESIGNER_BACKEND_URL=${DESIGNER_BACKEND_URL}
      - DESIGNER_BACKEND_KEY=${DESIGNER_BACKEND_KEY}
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - ADMIN_SECRET=${ADMIN_SECRET}
    depends_on:
      - mongodb-workbench
    ports:
      - '${PORT_WORKBENCH_BACKEND}:80'
    networks:
      - leia-workbench-network

  runner:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-runner:latest
    container_name: runner-workbench
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=${NODE_ENV}
      - PORT=80
      - RUNNER_KEY=${RUNNER_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EVALUATION_MODEL=${OPENAI_EVALUATION_MODEL:-gpt-4o}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-openai}
    depends_on:
      - redis
    ports:
      - '${PORT_RUNNER}:80'
    networks:
      - leia-workbench-network

  # FRONTEND SERVICES
  workbench-frontend:
    restart: unless-stopped
    image: ghcr.io/leia-org/leia-workbench-frontend:latest
    container_name: workbench-frontend
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${PORT_WORKBENCH_FRONTEND}:3000'
    networks:
      - leia-workbench-network

volumes:
  mongo-workbench:
  redis-data:

networks:
  leia-workbench-network:
    driver: bridge
